# Generated by Django 5.0 on 2023-12-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "watchlist_app",
            "0003_alter_platform_options_remove_watchlist_platform_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
