# Generated by Django 5.0 on 2023-12-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0004_alter_platform_name_alter_watchlist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Movie Name"
            ),
        ),
    ]
